---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
    exclude_paths:
      - 'spec/'
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  rubocop:
    Enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.coffee"
  - "**.css"
  - "**.erb"
  - "**.js"
  - "**.markdown"
  - "**.md"
  - "**.rake"
  - "**.rb"
  - "**.scss"
  - "**.sh"
exclude_paths:
- docs/v3/node_modules/
- errors/
